import { DummyButton } from "../types/dummyDataTypes";

export const DummyCategories: DummyButton[] = [
  {
    label: "Kick offs",
    id: 1,
    onClick: () => alert("Kick offs clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Starters",
    id: 2,
    onClick: () => alert("Starters clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Main Courses",
    id: 3,
    onClick: () => alert("Main Courses clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Desserts",
    id: 4,
    onClick: () => alert("Desserts clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Kids menu",
    id: 5,
    onClick: () => alert("Kids menu clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Beer",
    id: 6,
    onClick: () => alert("Beer clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Wine",
    id: 7,
    onClick: () => alert("Wine clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Spirits",
    id: 8,
    onClick: () => alert("Spirits clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Soft Drinks",
    id: 9,
    onClick: () => alert("Soft Drinks clicked"),
    bgColor: "bg-[#1E3A8A]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
  {
    label: "Hot Drinks",
    id: 10,
    onClick: () => alert("Hot Drinks clicked"),
    bgColor: "bg-[#A32616]",
    textColor: "text-white",
    font: "",
    textSize: "text-base",
    colSpan: 1,
  },
];
