import { Recipe } from "../types/recipeTypes";

export const DummyRecipes: Recipe[] = [
  {
    name: "Spaghetti Bolognese",
    id: 1,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.8,
    salePrice: 7.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Chicken Curry",
    id: 2,
    subDivisionId: 1,
    version: 1,
    costPrice: 3.1,
    salePrice: 8.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Vegetable Stir Fry",
    id: 3,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.2,
    salePrice: 6.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Beef Tacos",
    id: 4,
    subDivisionId: 1,
    version: 1,
    costPrice: 3.5,
    salePrice: 9,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Caesar Salad",
    id: 5,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.7,
    salePrice: 7,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Margherita Pizza",
    id: 6,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.9,
    salePrice: 7.5,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Grilled Salmon",
    id: 7,
    subDivisionId: 1,
    version: 1,
    costPrice: 4.8,
    salePrice: 12,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Lentil Soup",
    id: 8,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.9,
    salePrice: 7.5,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Pork Chops",
    id: 9,
    subDivisionId: 1,
    version: 1,
    costPrice: 4.8,
    salePrice: 12.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Fish and Chips",
    id: 10,
    subDivisionId: 1,
    version: 1,
    costPrice: 3.9,
    salePrice: 10,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Chicken Alfredo",
    id: 11,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.6,
    salePrice: 7.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Vegetable Lasagna",
    id: 12,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.5,
    salePrice: 7.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Shrimp Scampi",
    id: 13,
    subDivisionId: 1,
    version: 1,
    costPrice: 4.2,
    salePrice: 10.5,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Beef Stroganoff",
    id: 14,
    subDivisionId: 1,
    version: 1,
    costPrice: 3.7,
    salePrice: 9.5,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Quinoa Salad",
    id: 15,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.9,
    salePrice: 7.5,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Stuffed Bell Peppers",
    id: 16,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.8,
    salePrice: 7.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Chicken Fajitas",
    id: 17,
    subDivisionId: 1,
    version: 1,
    costPrice: 3.1,
    salePrice: 8,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Mushroom Risotto",
    id: 18,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.6,
    salePrice: 7.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Pasta Primavera",
    id: 19,
    subDivisionId: 1,
    version: 1,
    costPrice: 3.2,
    salePrice: 8,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "BBQ Ribs",
    id: 20,
    subDivisionId: 1,
    version: 1,
    costPrice: 4.2,
    salePrice: 12,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
];

export const AltDummyProducts: Recipe[] = [
  {
    name: "Special Starter",
    id: 21,
    subDivisionId: 1,
    version: 1,
    costPrice: 1.5,
    salePrice: 4.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Special Mains",
    id: 22,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.0,
    salePrice: 5.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Special Burger",
    id: 23,
    subDivisionId: 1,
    version: 1,
    costPrice: 2.5,
    salePrice: 6.0,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
  {
    name: "Steak Dessert",
    id: 24,
    subDivisionId: 1,
    version: 1,
    costPrice: 1.8,
    salePrice: 4.5,
    RecipeIngredient: [],
    recipeAllergens: [],
    recipeDietaryTags: [],
    userNotes: [],
  },
];
