export const MODAL_PAGES = {
  PRODUCT_LIST: "PRODUCT_LIST",
  EDIT_PRODUCT: "EDIT_PRODUCT",
};

export const EDIT_TYPES = {
  OVERVIEW: "OVERVIEW",
  ADD_NOTE: "ADD_NOTE",
  ADD_ALLERGY: "ADD_ALLERGY",
  EDIT_INGREDIENTS: "EDIT_INGREDIENTS",
};
